version: 2.1

defaults: &defaults
  working_directory: ~/twilio-flex-spoke-directory-plugin
  docker:
    # Twilio's serverless runtime environment runs on node 12, so we keep it consistent here
    - image: circleci/node:12

aliases:
  - &npmrc # TODO remove once we have public versions of the plugin and functions packages
    name: Link npmrc
    command: |
      echo "@spoke-ph:registry=https://registry.npmjs.org/" \>> ~/.npmrc
      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" \>> ~/.npmrc
  - &install_twilio_cli
    name: Install twilio cli and plugins
    command: |
      npm i --prefix=$HOME/.local -g twilio-cli
      twilio plugins:install @twilio-labs/plugin-serverless
      twilio plugins:install @twilio-labs/plugin-flex
  - &generate_function_env_file
    name: Generate function .env file
    command: |
      ENV_PATH=./functions/.env
      echo "SPOKE_CLIENT_ID=$SPOKE_CLIENT_ID" >> $ENV_PATH
      echo "SPOKE_CLIENT_SECRET=$SPOKE_CLIENT_SECRET" >> $ENV_PATH
      echo "SPOKE_AUTH_SERVICE_URL=$SPOKE_AUTH_SERVICE_URL" >> $ENV_PATH
      echo "SPOKE_API_URL=$SPOKE_API_URL" >> $ENV_PATH
      echo "ACCOUNT_SID=$TWILIO_ACCOUNT_SID" >> $ENV_PATH
      echo "AUTH_TOKEN=$TWILIO_AUTH_TOKEN" >> $ENV_PATH
  - &generate_plugin_env_file
    name: Generate plugin .env file
    command: |
      ENV_PATH=./.env
      echo "FLEX_APP_FUNCTIONS_BASE_URL=$FLEX_APP_FUNCTIONS_BASE_URL" >> $ENV_PATH
      echo "FLEX_APP_CALLER_ID=$FLEX_APP_CALLER_ID" >> $ENV_PATH
  - &filter_untagged_commits_on_master_branch
    filters:
      branches:
        only: master
      tags:
        only: /^$/ # don't run on tagged commit

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *npmrc
      - run: *generate_function_env_file
      - run: *generate_plugin_env_file
      - run:
          name: NPM Install
          command: npm ci
      - run: *install_twilio_cli
      - run:
          name: Build serverless functions
          command: npm run functions:build
      - run:
          name: Build Flex plugin
          command: npm run plugin:build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/twilio-flex-spoke-directory-plugin
      - run: *generate_function_env_file
      - run: *generate_plugin_env_file
      - run: *install_twilio_cli
      - run:
          name: Build and deploy functions
          command: npm run functions:deploy
      - run:
          name: Build, deploy and release plugin
          command: CHANGELOG=`git log --format=%s -1` npm run plugin:deploy && npm run plugin:release

  tag:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Tag version
          command: |
            VERSION=`npm --loglevel silent run version`
            echo $VERSION
            if [[ ("${CIRCLE_BRANCH}" == "master") && ($VERSION != *"SNAPSHOT") ]]; then
              npm --loglevel silent run version | xargs -I {} git tag "v{}"
              git push origin --tags
            else
              echo "Skip as branch not master"
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context:
            - org-global
            - directory-flex-plugin
      - deploy:
          context:
            - org-global
            - directory-flex-plugin
          requires:
            - build
          <<: *filter_untagged_commits_on_master_branch
  tag:
    jobs:
      - tag:
          context: org-global
          <<: *filter_untagged_commits_on_master_branch
